// M7004InstPrinter.h - M7004 InstPrinter (scaffolded from Fe)
#ifndef LLVM_LIB_TARGET_M7004_MCTARGETDESC_M7004INSTPRINTER_H
#define LLVM_LIB_TARGET_M7004_MCTARGETDESC_M7004INSTPRINTER_H

#include "MCTargetDesc/M7004MCTargetDesc.h"
#include "llvm/MC/MCInstPrinter.h"
#include <unordered_map>
#include <string>

namespace llvm {
class M7004InstPrinter : public MCInstPrinter {
public:
  M7004InstPrinter(const MCAsmInfo &MAI, const MCInstrInfo &MII,
                   const MCRegisterInfo &MRI)
      : MCInstPrinter(MAI, MII, MRI), MyMap(dummyMap){}

  M7004InstPrinter(const MCAsmInfo &MAI, const MCInstrInfo &MII,
                   const MCRegisterInfo &MRI,
                   std::unordered_map<unsigned int, std::string> &Map);

  // Autogenerated by tblgen.
  void printInstruction(const MCInst *MI, uint64_t Address, raw_ostream &O);
  static const char *getRegisterName(MCRegister Reg);
  static const char* getRegisterName(MCRegister Reg, unsigned AltIdx);
  void printMemOperand(const MCInst *MI, unsigned OpNo, raw_ostream &O);
  void printRtoRmemOperand(const MCInst *MI, unsigned OpNo, raw_ostream &O);
  void printBaseMemOperand(const MCInst *MI, unsigned OpNo, raw_ostream &O);
  void printPtrOperand(const MCInst *MI, unsigned OpNo, raw_ostream &O);
  void printRegName(raw_ostream &OS, MCRegister Reg) const override;
  void printInst(const MCInst *MI, uint64_t Address, StringRef Annot,
                 const MCSubtargetInfo &STI, raw_ostream &O) override;

  bool printAliasInstr(const MCInst *MI, uint64_t Address, raw_ostream &OS);
  void printCustomAliasOperand(const MCInst *MI, uint64_t Address,
                               unsigned OpIdx, unsigned PrintMethodIdx,
                               raw_ostream &O);

  std::pair<const char *, uint64_t> getMnemonic(const MCInst *MI) override;
  void printBranchOperand(const MCInst *MI, unsigned OpNo, raw_ostream &O);
private:
  std::unordered_map<unsigned int, std::string> &MyMap;
  static std::unordered_map<unsigned int, std::string> dummyMap;
  void printOperand(const MCInst *MI, unsigned OpNo, raw_ostream &O);
  void printImmediate(const MCInst *MI, unsigned opNum, raw_ostream &O);
  void printFPImmOperand(const MCInst *MI, unsigned OpNo, raw_ostream &O);
};
}

#endif // LLVM_LIB_TARGET_M7004_MCTARGETDESC_M7004INSTPRINTER_H
